
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: source-consumer
  mvc:
    view:
      prefix: /
      suffix: .jsp
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 250 # 连接超时时间(ms)
    ReadTimeout: 1000 # 通信超时时间(ms)
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能